version: "3.8"

services:
    mongodb:
        image: mongo:3.6.8
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - db:/data/db
        networks:
            - backend
    back:
        depends_on:
            - mongodb
        build: ./back
        ports:
            - "9000:9000"
        networks:
            - backend
            - frontend
        restart: on-failure
    front:
        depends_on:
            - back
        build: ./front
        ports:
            - "80:80"
        networks:
            - frontend
        restart: unless-stopped
volumes:
    db:
        driver: local

networks:
    backend:
        driver: bridge
    frontend:
