version: "3.8"

services:
    mongodb:
        image: mongo:3.6.8
        restart: unless-stopped
        env_file: ./.env
        environment:
            - DB_HOST=$DB_HOST
            - DB_NAME=$DB_NAME
            - DB_PORT=$DB_PORT
        ports:
            - $DB_PORT:$DB_PORT
        volumes:
            - db:/data/db
        networks:
            - backend
    back:
        depends_on:
            - mongodb
        build:
            context: ./back
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $API_PORT:$API_PORT
        environment:
            - API_PORT=$API_PORT
            - APP_SECRET=$APP_SECRET
            - FRONT_ORIGIN=$FRONT_ORIGIN
        volumes:
            - ./back:/usr/src/back
            - /usr/src/back/node_modules
        networks:
            - backend
            - frontend

    front:
        depends_on:
            - back
        env_file: ./.env
        build:
            context: ./front
            dockerfile: Dockerfile
            args:
                - API_URL=$API_URL
        ports:
            - $FRONT_PORT:$FRONT_PORT
        environment:
            - FRONT_PORT=$FRONT_PORT
            - API_URL=$API_URL
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./front:/usr/src/front
            - /usr/src/front/node_modules
        networks:
            - frontend

volumes:
    db:
        driver: local

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
